version = 0.1

[default]
[default.global.parameters]
stack_name = "size-recommendation-api"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "ap-south-1"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "CheckpointPath=\"s3://size-recommendation-models/models/best_model.pth\""
s3_prefix = "size-recommendation-api"
disable_rollback = true
image_repositories = []

